services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    env_file: .neo4j.env # In this env, provide NEO4J_AUTH=user/password
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/import
      - ./neo4j/plugins:/plugins
      - ./data:/external-data # Mounting this to be able to load the data from the host

  etl:
    build: .  # Use the shared Dockerfile
    container_name: etl
    restart: always
    depends_on:
      - neo4j
    command: ["python", "etl_script.py"]  

  # streamlit:
  #   build: .  # Use the shared Dockerfile
  #   container_name: streamlit
  #   restart: always
  #   ports:
  #     - "8501:8501"
  #   depends_on:
  #     - neo4j
  #   command: ["streamlit", "run", "home.py"]  